### PR TITLE
3box to dao layout header

### LINKED ISSUE #1871: Bug: Hub "Edit 3Box Profile" links to self.id
**Describe the bug**
The button to edit 3box profile links to the wrong place

**To Reproduce**
1. Go to Hub
2. Click on "Edit 3Box Profile"
3. See that you are directed to self.id

**Expected behavior**

Member profile update flow is presented to user clicking on button.

**Actual behavior**

Linked to self.id website

**Screenshots**

**Application area**

Where in the app is this happening?
- FrontEnd (please include route/section if possible)

**Additional context**

From @Keating
> For V2 can remove or change where edit 3Box profile redirects to? It should redirect to our member profile update flow rather than self.id https://cdn.discordapp.com/attachments/899436946143723521/980529776513122304/profile.png

# Detials

Screen Shot 2022-07-02 at 3 10 39 PM
Screen Shot 2022-07-02 at 3 10 54 PM
Screen Shot 2022-07-02 at 3 11 07 PM

### PR DESCRIPTION
**Pull request by brossetti1**
## GitHub Issue

fixes https://github.com/HausDAO/daohaus-app/issues/1871

## Changes

WIP see issue for details

## Checks

Before making your PR, please check the following:

- [ ] Critical lint errors are resolved
- [ ] App runs and builds locally

### CODE REVIEW

File: src/components/pageHeader.jsx [hunk 1]
```diff
@@ -23,6 +40,11 @@ const PageHeader = ({ isDao, header, headerEl, customTerms }) => {
         >
           {customTerms ? getTerm(customTerms, header) : header}
         </Box>
+        {isDao && (
+          <Button onClick={handleEditProfile} mr={5} variant='outline'>
+            Edit 3Box Profile
```
Comment (skuhlmann) [inline src/components/pageHeader.jsx]: Do we really want this on all DAO pages?

If so, could we just change this to 'Edit Profile'

Comment (brossetti1) [reply src/components/pageHeader.jsx]: just updated this on the latest commit 693097f

discord response: https://discord.com/channels/709210493549674598/969251831752568903/994373323150606478

**Review by skuhlmann — APPROVED** [review]
