### PR TITLE
Fix/navbar lag

### LINKED ISSUE #1862: Bug: navbar lags when switching to DAO
**Describe the bug**
The nav was designed was designed to change with the routes. 

See why it's now changing once the DAO loads its graph data.  

Needs exploration.

**To Reproduce**
1. Go to hub
2. Click on a DAO
3. See hub navbar shortly then DAO specific nav after lag

**Expected behavior**

Nav should have default elements based on route, boosts and DAO specific nav can load after graph data loads.

**Actual behavior**

Wrong nav is showing and then the correct navbar replaces it after lag.

**Screenshots**

Loom showing behavior: https://www.loom.com/share/6a35bbb21da44b9ab25da68523f7adcc

**Application area**

Where in the app is this happening?
- FrontEnd (please include route/section if possible)
- Subgraph

### PR DESCRIPTION
**Pull request by cgonel**
## GitHub Issue

#1862 

## Changes

Added a function in navLinks.js to show the basic dao links until the vaults data is loaded.

## Checks

Before making your PR, please check the following:

- [x] Critical lint errors are resolved
- [x] App runs and builds locally

### CODE REVIEW

**Comment by plor** [comment]
Thanks for this @cgonel! I've moved to review.

File: src/utils/navLinks.js [hunk 1]
```diff
@@ -17,6 +17,11 @@ import {
 import { FaDiscourse } from 'react-icons/fa';
 
 // no slash on the path
+export const defaultDaoDataLoading = [
+  { icon: RiTeamLine, label: 'Members', path: 'members' },
+  { icon: RiSettings3Line, label: 'Settings', path: 'settings' },
+  { icon: RiRocket2Line, label: 'Boosts', path: 'settings/boosts' },
+];
```
Comment (plor) [inline src/utils/navLinks.js]: I think "gallery" and "documents" are the only links that shouldn't be displayed by default. Then those are added if the requirements are met. I think rather than duplicating the data, extract the two non-default and add them in through that function.

**Review by plor — CHANGES_REQUESTED** [review]
Looks great to me. The only thing is that the dao links should include what I noted, the only reason it wasn't was because that generator required data. I think separating this would be much cleaner.

**Review by plor — APPROVED** [review]
This looks much cleaner to me! 👍
